name: selfmemory_flutter
description: Our Self Memory app native.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  fluttertoast:
  path:
  http:
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - logo.png
    - assets/images/

  fonts:
    - family: Anonymous
      fonts:
        - asset: assets/fonts/Anonymous_Pro.ttf
        - asset: assets/fonts/Anonymous_Pro_B.ttf
        - asset: assets/fonts/Anonymous_Pro_BI.ttf
        - asset: assets/fonts/Anonymous_Pro_I.ttf
          weight: 400
